dateModified: 0
email:
  fromEmail: support@iceweb.co
  fromName: 'Craft CMS'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  schemaVersion: 3.5.13
  timeZone: Asia/Riyadh
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
